name: e_commerce_design1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  http: ^1.5.0
  provider: ^6.1.5+1
  readmore: ^3.0.0
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
